### ISSUE TITLE
Error sending output to Messenger for users other than myself

### ISSUE THREAD

**Issue by johmca** [ibm-early-programs/node-red-contrib-facebook-messenger-writer#5]
Hi 

I've been following the DW Basics to Bots course and used this node as part of the lab solutions without any problem. I'm now trying to develop the lab solution further and I'd like other Facebook users to be able to interact with my bot.  Unfortunately when another user sends a message the node-red-contrib-facebook-messenger-writer node stops processing with an error. In both cases the node uses the same Facebook Page Access Token. In both cases the FacebookEvent object has been set to equal the incoming MessagingEvent object so the SenderID should be correct and correspodn the the message sender correctly. 

When I send a message to the bot it works fine and makes a response correctly. It is only when someone else sends the message that it shows the error. I'm afraid I don't know how to gather more details about the error (it just appears below the node stating Error and not much more)

Can you provide any guidance on this?

**Comment by chughts** [comment]
This is a restriction imposed by Facebook. Facebook allows you to create and test bots, but if you want other people to use them, then you will need to certify your bot with Facebook.

**Comment by johmca** [comment]
Thanks for your quick response. That does appear to be the problem.
