### ISSUE TITLE
Example of usage

### ISSUE THREAD

**Issue by hakey1408** [ibm-early-programs/node-red-contrib-facebook-messenger-writer#6]
Hi!
I'm writing a chatbot with watson and node-red but i didn't understand how to use this node ... i'm kinda new to this type of things.
Could you provide a simple and working example of flow using this node?
I don't know how to "link" node-red to messenger, especially with the HTTP GET part because i need a webhook to make it works. I already have a page access token.
Summary:

I have:

- working conversation and working node of IBM watson.

- page access token

- node-red deployed on bluemix

I don't know how to use:

- HTTP GET to get the message of a user from messenger (I need a webhook and a verify token too)

- This node to send the message to the user as a response (coming from Watson node)

Thank you in advance!

**Comment by chughts** [comment]
There is a whole course dedicated to this - https://developer.ibm.com/courses/all-courses/node-red-basics-bots/
