### ISSUE TITLE
Is it still working?

### ISSUE THREAD

**Issue by slin999** [ibm-early-programs/node-red-contrib-facebook-messenger-writer#7]
I receive Error Sending Message on the bottom with the following pre-filtering function: 

msg.facebookevent = {
    "sender": { "id": "1421505421223327" } //The recipient id of the message received
};
msg.payload = msg.payload.text[0];
return msg;

With the following access token:
EAAPT98lf9dcBALhTZAFrKZB3kVMoZAll7ZCHWszUDWtHOgcZBWZAu6vWjniDJQfOyyJChJljVowfYnlDfZAIs0issqdfKZB09BpZBZCZAF22aZBoFpijOAF1zLIMvDKCTEcfQIeJAsgApysFT8w7TKJ27eYF4UfQkU4O2EnW5e8aS9zkMQZDZD

**Comment by chughts** [comment]
This issues repo is for bugs in the code or improvement requests. Unless you can tell which line is in error then I am going to treat this as a usage question. 

I don't answer usage questions here. Please raise on http://developer.ibm.com/answers and I will help you as much as I can. You can post the question url here. If we determine that it is a bug, then I will gladly reopen this issue.

You should also consider the Basic to Bots course, module 4 shows how to use the node. https://developer.ibm.com/courses/all-courses/node-red-basics-bots/
